#include<iostream>
using namespace std;
int main()
{
		int firstNumber;
	firstNumber=1;
	cout<<firstNumber;
	cout<<endl;
	
	int secondNumber;
	secondNumber=2;
	cout<<secondNumber;
	cout<<endl;
	
	int thirdNumber;
	thirdNumber=3;
	cout<<thirdNumber;
	cout<<endl;
	
	int fourthNumber;
	fourthNumber=4;
	cout<<fourthNumber;
	cout<<endl;
	
	int fifthNumber;
	fifthNumber=5;
	cout<<fifthNumber;
	cout<<endl;
	
	int sixthNumber;
	sixthNumber=6;
	cout<<sixthNumber;
	cout<<endl;
	
	int seventhNumber;
	seventhNumber=7;
	cout<<seventhNumber;
	cout<<endl;
	
	int eightthNumber;
	eightthNumber=8;
	cout<<eightthNumber;
	cout<<endl;
	
	int ninthNumber;
	ninthNumber=9;
	cout<<ninthNumber;
	cout<<endl;
	
	int tenthNumber;
	tenthNumber=10;
	cout<<tenthNumber;
	cout<<endl;
	
	int eleventhNumber;
	eleventhNumber=11;
	cout<<eleventhNumber;
	cout<<endl;
	
	int twelvethNumber;
	twelvethNumber=12;
	cout<<twelvethNumber;
	cout<<endl;
	
	int thirteenthNumber;
	thirteenthNumber=13;
	cout<<thirteenthNumber;
	cout<<endl;
	
	int fourteenthNumber;
	fourteenthNumber=14;
	cout<<fourteenthNumber;
	cout<<endl;
	
	int fifteenthNumber;
	fifteenthNumber=15;
	cout<<fifteenthNumber;
	cout<<endl;
	
	int sixteenthNumber;
	sixteenthNumber=16;
	cout<<sixteenthNumber;
	cout<<endl;
	
	int seventeenthNumber;
	seventeenthNumber=17;
	cout<<seventeenthNumber;
	cout<<endl;
	
	int eighteenthNumber;
	eighteenthNumber=18;
	cout<<eighteenthNumber;
	cout<<endl;
	
	int ninteenthNumber;
	ninteenthNumber=19;
	cout<<ninteenthNumber;
	cout<<endl;
	
	int twentythNumber;
	twentythNumber=20;
	cout<<twentythNumber;
	cout<<endl;
	
	int twentyfirstNumber;
	twentyfirstNumber=21;
	cout<<twentyfirstNumber;
	cout<<endl;
	
	int twentysecondNumber;
	twentysecondNumber=22;
	cout<<twentysecondNumber;
	cout<<endl;
	
	int twentythirdNumber;
	firstNumber=23;
	cout<<twentythirdNumber;
	cout<<endl;
	
	int twentyfourthNumber;
	twentyfourthNumber=24;
	cout<<twentyfourthNumber;
	cout<<endl;
	
	int twentyfifthNumber;
	twentyfifthNumber=25;
	cout<<twentyfifthNumber;
	cout<<endl;
	
	int twentysixthNumber;
	twentysixthNumber=26;
	cout<<twentysixthNumber;
	cout<<endl;
	
	int twentyseventhNumber;
	twentyseventhNumber=27;
	cout<<twentyseventhNumber;
	cout<<endl;
	
	int twentyeightthNumber;
	twentyeightthNumber=28;
	cout<<twentyeightthNumber;
	cout<<endl;
	
	int twentyninthNumber;
	twentyninthNumber=29;
	cout<<twentyninthNumber;
	cout<<endl;
	
	int thirtythNumber;
	thirtythNumber=30;
	cout<<thirtythNumber;
	cout<<endl;
	
	int thirtyfirstNumber;
	thirtyfirstNumber=31;
	cout<<thirtyfirstNumber;
	cout<<endl;
	
	int thirtysecondNumber;
	thirtysecondNumber=32;
	cout<<thirtysecondNumber;
	cout<<endl;
	
	int thirtythirdNumber;
	thirtythirdNumber=33;
	cout<<thirtythirdNumber;
	cout<<endl;
	
	int thirtyfourthNumber;
	thirtyfourthNumber=34;
	cout<<thirtyfourthNumber;
	cout<<endl;
	
	int thirtyfifthNumber;
	thirtyfifthNumber=35;
	cout<<thirtyfifthNumber;
	cout<<endl;
	
	int thirtysixthNumber;
	thirtysixthNumber=36;
	cout<<thirtysixthNumber;
	cout<<endl;
	
	int thirtyseventhNumber;
	thirtyseventhNumber=37;
	cout<<thirtyseventhNumber;
	cout<<endl;
	
	int thirtyeightthNumber;
	thirtyeightthNumber=38;
	cout<<thirtyeightthNumber;
	cout<<endl;
	
	int thirtyninthNumber;
	thirtyninthNumber=39;
	cout<<thirtyninthNumber;
	cout<<endl;
	
	int fourtythNumber;
	fourtythNumber=40;
	cout<<fourtythNumber;
	cout<<endl;
	
	int fourtyfirstNumber;
	fourtyfirstNumber=41;
	cout<<fourtyfirstNumber;
	cout<<endl;
	
	int fourtysecondNumber;
	fourtysecondNumber=42;
	cout<<fourtysecondNumber;
	cout<<endl;
	
	int fourtythirdNumber;
	fourtythirdNumber=43;
	cout<<fourtythirdNumber;
	cout<<endl;
	
	int fourtyfourthNumber;
	fourtyfourthNumber=44;
	cout<<fourtyfourthNumber;
	cout<<endl;
	
	int fourtyfifthNumber;
	fourtyfifthNumber=45;
	cout<<fourtyfifthNumber;
	cout<<endl;
	
	int fourtysixthNumber;
	fourtysixthNumber=46;
	cout<<fourtysixthNumber;
	cout<<endl;
	
	int fourtyseventhNumber;
	fourtyseventhNumber=47;
	cout<<fourtyseventhNumber;
	cout<<endl;
	
	int fourtyeightthNumber;
	fourtyeightthNumber=48;
	cout<<fourtyeightthNumber;
	cout<<endl;
	
	int fourtyninthNumber;
	fourtyninthNumber=49;
	cout<<fourtyninthNumber;
	cout<<endl;
	
	int fiftythNumber;
	fiftythNumber=50;
	cout<<fiftythNumber;
	cout<<endl;
	
	int fiftyfirstNumber;
	fiftyfirstNumber=51;
	cout<<fiftyfirstNumber;
	cout<<endl;
	
	int fiftysecondNumber;
	fiftysecondNumber=52;
	cout<<fiftysecondNumber;
	cout<<endl;
	
	int fiftythirdNumber;
	fiftythirdNumber=53;
	cout<<fiftythirdNumber;
	cout<<endl;
	
	int fiftyfourthNumber;
	fiftyfourthNumber=54;
	cout<<fiftyfourthNumber;
	cout<<endl;
	
	int fiftyfifthNumber;
	fiftyfifthNumber=55;
	cout<<fiftyfifthNumber;
	cout<<endl;
	
	int fiftysixthNumber;
	fiftysixthNumber=56;
	cout<<fiftysixthNumber;
	cout<<endl;
	
	int fiftyseventhNumber;
	fiftyseventhNumber=57;
	cout<<fiftyseventhNumber;
	cout<<endl;
	
	int fiftyeightthNumber;
	fiftyeightthNumber=58;
	cout<<fiftyeightthNumber;
	cout<<endl;
	
	int fiftyninthNumber;
	fiftyninthNumber=59;
	cout<<fiftyninthNumber;
	cout<<endl;
	
	int sixtythNumber;
	sixtythNumber=60;
	cout<<sixtythNumber;
	cout<<endl;
	
	int sixtyfirstNumber;
	sixtyfirstNumber=61;
	cout<<sixtyfirstNumber;
	cout<<endl;
	
	int sixtysecondNumber;
	sixtysecondNumber=62;
	cout<<sixtysecondNumber;
	cout<<endl;
	
	int sixtythirdNumber;
	sixtythirdNumber=63;
	cout<<sixtythirdNumber;
	cout<<endl;
	
	int sixtyfourthNumber;
	sixtyfourthNumber=64;
	cout<<sixtyfourthNumber;
	cout<<endl;
	
	int sixtyfifthNumber;
	sixtyfifthNumber=65;
	cout<<sixtyfifthNumber;
	cout<<endl;
	
	int sixtysixthNumber;
	sixtysixthNumber=66;
	cout<<sixtysixthNumber;
	cout<<endl;
	
	int sixtyseventhNumber;
	sixtyseventhNumber=67;
	cout<<sixtyseventhNumber;
	cout<<endl;
	
	int sixtyeightthNumber;
	sixtyeightthNumber=68;
	cout<<sixtyeightthNumber;
	cout<<endl;
	
	int sixtyninthNumber;
	sixtyninthNumber=69;
	cout<<sixtyninthNumber;
	cout<<endl;
	
	int seventythNumber;
	seventythNumber=70;
	cout<<seventythNumber;
	cout<<endl;
	
	int seventyfirstNumber;
	seventyfirstNumber=71;
	cout<<seventyfirstNumber;
	cout<<endl;
	
	int seventysecondNumber;
	seventysecondNumber=72;
	cout<<seventysecondNumber;
	cout<<endl;
	
	int seventythirdNumber;
	seventythirdNumber=73;
	cout<<seventythirdNumber;
	cout<<endl;
	
	int seventyfourthNumber;
	seventyfourthNumber=74;
	cout<<seventyfourthNumber;
	cout<<endl;
	
	int seventyfifthNumber;
	seventyfifthNumber=75;
	cout<<seventyfifthNumber;
	cout<<endl;
	
	int seventysixthNumber;
	seventysixthNumber=76;
	cout<<seventysixthNumber;
	cout<<endl;
	
	int seventyseventhNumber;
	seventyseventhNumber=77;
	cout<<seventyseventhNumber;
	cout<<endl;
	
	int seventyeightthNumber;
	seventyeightthNumber=78;
	cout<<seventyeightthNumber;
	cout<<endl;
	
	int seventyninthNumber;
	seventyninthNumber=79;
	cout<<seventyninthNumber;
	cout<<endl;
	
	int eightythNumber;
	eightythNumber=80;
	cout<<eightythNumber;
	cout<<endl;
	
	int eightyfirstNumber;
	eightyfirstNumber=81;
	cout<<eightyfirstNumber;
	cout<<endl;
	
	int eightysecondNumber;
	eightysecondNumber=82;
	cout<<eightysecondNumber;
	cout<<endl;
	
	int eightythirdNumber;
	eightythirdNumber=83;
	cout<<eightythirdNumber;
	cout<<endl;
	
	int eightyfourthNumber;
	eightyfourthNumber=84;
	cout<<eightyfourthNumber;
	cout<<endl;
	
	int eightyfifthNumber;
	eightyfifthNumber=85;
	cout<<eightyfifthNumber;
	cout<<endl;
	
	int eightysixthNumber;
	eightysixthNumber=86;
	cout<<eightysixthNumber;
	cout<<endl;
	
	int eightyseventhNumber;
	eightyseventhNumber=87;
	cout<<eightyseventhNumber;
	cout<<endl;
	
	int eightyeightthNumber;
	eightyeightthNumber=88;
	cout<<eightyeightthNumber;
	cout<<endl;
	
	int eightyninthNumber;
	eightyninthNumber=89;
	cout<<eightyninthNumber;
	cout<<endl;
	
	int nintythNumber;
	nintythNumber=90;
	cout<<nintythNumber;
	cout<<endl;
	
	int nintyfirstNumber;
	nintyfirstNumber=91;
	cout<<nintyfirstNumber;
	cout<<endl;
	
	int nintysecondNumber;
	nintysecondNumber=92;
	cout<<nintysecondNumber;
	cout<<endl;
	
	int nintythirdNumber;
	nintythirdNumber=93;
	cout<<nintythirdNumber;
	cout<<endl;
	
	int nintyfourthNumber;
	nintyfourthNumber=94;
	cout<<nintyfourthNumber;
	cout<<endl;
	
	int nintyfifthNumber;
	nintyfifthNumber=95;
	cout<<nintyfifthNumber;
	cout<<endl;
	
	int nintysixthNumber;
	nintysixthNumber=96;
	cout<<nintysixthNumber;
	cout<<endl;
	
	int nintyseventhNumber;
	nintyseventhNumber=97;
	cout<<nintyseventhNumber;
	cout<<endl;
	
	int nintyeightthNumber;
	nintyeightthNumber=98;
	cout<<nintyeightthNumber;
	cout<<endl;
	
	int nintyninthNumber;
	nintyninthNumber=99;
	cout<<nintyninthNumber;
	cout<<endl;
	
	int hundredthNumber;
	hundredthNumber=100;
	cout<<hundredthNumber;
	cout<<endl; 
 
	int hundredandfirstnumber;
	hundredandfirstnumber=101;
	cout<<hundredandfirstnumber;
	cout<<endl;
	int hundredandsecondnumber;
	hundredandsecondnumber=102;
	cout<<hundredandsecondnumber;
	cout<<endl;
	int hundredandthirdnumber;
	hundredandthirdnumber=103;
	cout<<hundredandthirdnumber;
	cout<<endl;
	int hundredandfourtnumber;
	hundredandfourtnumber=104;
	cout<<hundredandfourtnumber;
	cout<<endl;
	int hundredandfifthnumber;
	hundredandfifthnumber=105;
	cout<<hundredandfifthnumber;
	cout<<endl;
	int hundredandsixnumber;
	hundredandsixnumber=106;
	cout<<hundredandsixnumber;
	cout<<endl;
	int hundredandsevennumber;
	hundredandsevennumber=107;
	cout<<hundredandsevennumber;
	cout<<endl;
	int hundredandeightnumber;
	hundredandeightnumber=108;
	cout<<hundredandeightnumber;
	cout<<endl;
	int hundredandninenumber;
	hundredandninenumber=109;
	cout<<hundredandninenumber;
	cout<<endl;
	int hundredandtennumber;
	hundredandtennumber=110;
	cout<<hundredandtennumber;
	cout<<endl;
	int hundredandelevennumber;
	hundredandelevennumber=111;
	cout<<hundredandelevennumber;
	cout<<endl;
	int hundredandtewelenumber;
	hundredandtewelenumber=112;
	cout<<hundredandtewelenumber;
	cout<<endl;
	int hundredandthirteennumber;
	hundredandthirteennumber=113;
	cout<<hundredandthirteennumber;
	cout<<endl;	
	int hundredandfourteennumber;
	hundredandfourteennumber=114;
	cout<<hundredandfourteennumber;
	cout<<endl;
	int hundredandfifteennumber;
	hundredandfifteennumber=115;
	cout<<hundredandfifteennumber;
	cout<<endl;
	int hundredandsixteennumber;
	hundredandsixteennumber=116;
	cout<<hundredandsixteennumber;
	cout<<endl;
	int hundredandseventeennumber;
	hundredandseventeennumber=117;
	cout<<hundredandseventeennumber;
	cout<<endl;
	int hundredandeighteennumber;
	hundredandeighteennumber=118;
	cout<<hundredandeighteennumber;
	cout<<endl;
	int hundredandninteennumber;
	hundredandninteennumber=119;
	cout<<hundredandninteennumber;
	cout<<endl;
	int hundredandteventynumber;
	hundredandteventynumber=120;
	cout<<hundredandteventynumber;
	cout<<endl;
	int hundredandteventyonenumber;
	hundredandteventyonenumber=121;
	cout<<hundredandteventyonenumber;
	cout<<endl;
	int hundredandteventytwonumber;
	hundredandteventytwonumber=122;
	cout<<hundredandteventytwonumber;
	cout<<endl;
	int hundredandteventytreenumber;
	hundredandteventytreenumber=123;
	cout<<hundredandteventytreenumber;
	cout<<endl;
	int hundredandteventyfournumber;
	hundredandteventyfournumber=124;
	cout<<hundredandteventyfournumber;
	cout<<endl;
	int hundredandteventyfivenumber;
	hundredandteventyfivenumber=125;
	cout<<hundredandteventyfivenumber;
	cout<<endl;
	int hundredandteventysixnumber;
	hundredandteventysixnumber=126;
	cout<<hundredandteventysixnumber;
	cout<<endl;
	int hundredandteventysevennumber;
	hundredandteventysevennumber=127;
	cout<<hundredandteventysevennumber;
	cout<<endl;
	int hundredandteventyeightnumber;
	hundredandteventyeightnumber=128;
	cout<<hundredandteventyeightnumber;
	cout<<endl;
	int hundredandteventyninenumber;
	hundredandteventyninenumber=129;
	cout<<hundredandteventyninenumber;
	cout<<endl;
	int hundredandthirtynumber;
	hundredandthirtynumber=130;
	cout<<hundredandthirtynumber;
	cout<<endl;
	int hundredandthirtyonenumber;
	hundredandthirtyonenumber=131;
	cout<<hundredandthirtyonenumber;
	cout<<endl;
	int hundredandthirtytwonumber;
	hundredandthirtytwonumber=132;
	cout<<hundredandthirtytwonumber;
	cout<<endl;
	int hundredandthirtytreenumber;
	hundredandthirtytreenumber=133;
	cout<<hundredandthirtytreenumber;
	cout<<endl;
	int hundredandthirtyfournumber;
	hundredandthirtyfournumber=134;
	cout<<hundredandthirtyfournumber;
	cout<<endl;
	int hundredandthirtyfivenumber;
	hundredandthirtyfivenumber=135;
	cout<<hundredandthirtyfivenumber;
	cout<<endl;
	int hundredandthirtysixnumber;
	hundredandthirtysixnumber=136;
	cout<<hundredandthirtysixnumber;
	cout<<endl;
	int hundredandthirtysevennumber;
	hundredandthirtysevennumber=137;
	cout<<hundredandthirtysevennumber;
	cout<<endl;
	int hundredandthirtyeightnumber;
	hundredandthirtyeightnumber=138;
	cout<<hundredandthirtyeightnumber;
	cout<<endl;
	int hundredandthirtyninenumber;
	hundredandthirtyninenumber=139;
	cout<<hundredandthirtyninenumber;
	cout<<endl;
	int hundredandfourtynumber;
	hundredandfourtynumber=140;
	cout<<hundredandfourtynumber;
	cout<<endl;
	int hundredandfourtyonenumber;
	hundredandfourtyonenumber=141;
	cout<<hundredandfourtyonenumber;
	cout<<endl;
	int hundredandfourtytwonumber;
	hundredandfourtytwonumber=142;
	cout<<hundredandfourtytwonumber;
	cout<<endl;
	int hundredandfourtytreenumber;
	hundredandfourtytreenumber=143;
	cout<<hundredandfourtytreenumber;
	cout<<endl;
	int hundredandfourtyfournumber;
	hundredandfourtyfournumber=144;
	cout<<hundredandfourtyfournumber;
	cout<<endl;
	int hundredandfourtyfivenumber;
	hundredandfourtyfivenumber=145;
	cout<<hundredandfourtyfivenumber;
	cout<<endl;
	int hundredandfourtysixnumber;
	hundredandfourtysixnumber=146;
	cout<<hundredandfourtysixnumber;
	cout<<endl;
	int hundredandfourtysevennumber;
	hundredandfourtysevennumber=147;
	cout<<hundredandfourtysevennumber;
	cout<<endl;
	int hundredandfourtyeightnumber;
	hundredandfourtyeightnumber=148;
	cout<<hundredandfourtyeightnumber;
	cout<<endl;
	int hundredandfourtyninenumber;
	hundredandfourtyninenumber=149;
	cout<<hundredandfourtyninenumber;
	cout<<endl;
	int hundredandfiftynumber;
	hundredandfiftynumber=150;
	cout<<hundredandfiftynumber;
	cout<<endl;
    int hundredandfiftyonenumber;
	hundredandfiftyonenumber=151;
	cout<<hundredandfiftyonenumber;
	cout<<endl;	
	int hundredandfiftytwonumber;
	hundredandfiftytwonumber=152;
	cout<<hundredandfiftytwonumber;
	cout<<endl;
int hundredandfiftytreenumber;
	hundredandfiftytreenumber=153;
	cout<<hundredandfiftytreenumber;
	cout<<endl;
	int hundredandfiftyfournumber;
	hundredandfiftyfournumber=154;
	cout<<hundredandfiftyfournumber;
	cout<<endl;
	int hundredandfiftyfivenumber;
	hundredandfiftyfivenumber=155;
	cout<<hundredandfiftyfivenumber;
	cout<<endl;
	int hundredandfiftysixnumber;
	hundredandfiftysixnumber=156;
	cout<<hundredandfiftysixnumber;
	cout<<endl;
	int hundredandfiftysevennumber;
	hundredandfiftysevennumber=157;
	cout<<hundredandfiftysevennumber;
	cout<<endl;
	int hundredandfiftyeightnumber;
	hundredandfiftyeightnumber=158;
	cout<<hundredandfiftyeightnumber;
	cout<<endl;
	int hundredandfiftyninenumber;
	hundredandfiftyninenumber=159;
	cout<<hundredandfiftyninenumber;
	cout<<endl;
	int hundredandsixtynumber;
	hundredandsixtynumber=160;
	cout<<hundredandsixtynumber;
	cout<<endl;
	int hundredandsixtyonenumber;
	hundredandsixtyonenumber=161;
	cout<<hundredandsixtyonenumber;
	cout<<endl;
	int hundredandsixtytwonumber;
	hundredandsixtytwonumber=162;
	cout<<hundredandsixtytwonumber;
	cout<<endl;
	int hundredandsixtytreenumber;
	hundredandsixtytreenumber=163;
	cout<<hundredandsixtytreenumber;
	cout<<endl;
	int hundredandsixtyfournumber;
	hundredandsixtyfournumber=164;
	cout<<hundredandsixtyfournumber;
	cout<<endl;
	int hundredandsixtyfivenumber;
	hundredandsixtyfivenumber=165;
	cout<<hundredandsixtyfivenumber;
	cout<<endl;
	int hundredandsixtysixnumber;
	hundredandsixtysixnumber=166;
	cout<<hundredandsixtysixnumber;
	cout<<endl;
	int hundredandsixtysevennumber;
	hundredandsixtysevennumber=167;
	cout<<hundredandsixtysevennumber;
	cout<<endl;
	int hundredandsixtyeightnumber;
	hundredandsixtyeightnumber=168;
	cout<<hundredandsixtyeightnumber;
	cout<<endl;
	int hundredandsixtyninenumber;
	hundredandsixtyninenumber=169;
	cout<<hundredandsixtyninenumber;
	cout<<endl;
	int hundredandseventynumber;
	hundredandseventynumber=170;
	cout<<hundredandseventynumber;
	cout<<endl;
	int hundredandseventyonenumber;
	hundredandseventyonenumber=171;
	cout<<hundredandseventyonenumber;
	cout<<endl;
	int hundredandseventytwonumber;
	hundredandseventytwonumber=172;
	cout<<hundredandseventytwonumber;
	cout<<endl;
	int hundredandseventytreenumber;
	hundredandseventytreenumber=173;
	cout<<hundredandseventytreenumber;
	cout<<endl;
	int hundredandseventyfournumber;
	hundredandseventyfournumber=174;
	cout<<hundredandseventyfournumber;
	cout<<endl;
	int hundredandseventyfivenumber;
	hundredandseventyfivenumber=175;
	cout<<hundredandseventyfivenumber;
	cout<<endl;
	int hundredandseventysixnumber;
	hundredandseventysixnumber=176;
	cout<<hundredandseventysixnumber;
	cout<<endl;
	int hundredandseventysevennumber;
	hundredandseventysevennumber=177;
	cout<<hundredandseventysevennumber;
	cout<<endl;
	int hundredandseventyeightnumber;
	hundredandseventyeightnumber=178;
	cout<<hundredandseventyeightnumber;
	cout<<endl;
	int hundredandseventyninenumber;
	hundredandseventyninenumber=179;
	cout<<hundredandseventyninenumber;
	cout<<endl;
	int hundredandeightynumber;
	hundredandeightynumber=180;
	cout<<hundredandeightynumber;
	cout<<endl;
	int hundredandeightyonenumber;
	hundredandeightyonenumber=181;
	cout<<hundredandeightyonenumber;
	cout<<endl;
	int hundredandeightytwonumber;
	hundredandeightytwonumber=182;
	cout<<hundredandeightytwonumber;
	cout<<endl;
	int hundredandeightytreenumber;
	hundredandeightytreenumber=183;
	cout<<hundredandeightytreenumber;
	cout<<endl;
	int hundredandeightyfournumber;
	hundredandeightyfournumber=184;
	cout<<hundredandeightyfournumber;
	cout<<endl;
	int hundredandeightyfivenumber;
	hundredandeightyfivenumber=185;
	cout<<hundredandeightyfivenumber;
	cout<<endl;
	int hundredandeightysixnumber;
	hundredandeightysixnumber=186;
	cout<<hundredandeightysixnumber;
	cout<<endl;
	int hundredandeightysevennumber;
	hundredandeightysevennumber=187;
	cout<<hundredandeightysevennumber;
	cout<<endl;
	int hundredandeightyeightnumber;
	hundredandeightyeightnumber=188;
	cout<<hundredandeightyeightnumber;
	cout<<endl;
	int hundredandeightyninenumber;
	hundredandeightyninenumber=189;
	cout<<hundredandeightyninenumber;
	cout<<endl;
	int hundredandnintynumber;
	hundredandnintynumber=190;
	cout<<hundredandnintynumber;
	cout<<endl;
	int hundredandnintyonenumber;
	hundredandnintyonenumber=191;
	cout<<hundredandnintyonenumber;
	cout<<endl;
	int hundredandnintytwonumber;
	hundredandnintytwonumber=192;
	cout<<hundredandnintytwonumber;
	cout<<endl;
	int hundredandnintytreenumber;
	hundredandnintytreenumber=193;
	cout<<hundredandnintytreenumber;
	cout<<endl;
	int hundredandnintyfournumber;
	hundredandnintyfournumber=194;
	cout<<hundredandnintyfournumber;
	cout<<endl;
	int hundredandnintyfivenumber;
	hundredandnintyfivenumber=195;
	cout<<hundredandnintyfivenumber;
	cout<<endl;
	int hundredandnintysixnumber;
	hundredandnintysixnumber=196;
	cout<<hundredandnintysixnumber;
	cout<<endl;
	int hundredandnintysevennumber;
	hundredandnintysevennumber=197;
	cout<<hundredandnintysevennumber;
	cout<<endl;
	int hundredandnintyeightynumber;
	hundredandnintyeightynumber=198;
	cout<<hundredandnintyeightynumber;
	cout<<endl;
	int hundredandnintyninenumber;
	hundredandnintyninenumber=199;
	cout<<hundredandnintyninenumber;
	cout<<endl;
	int twohundredandnumber;
	twohundredandnumber=200;
	cout<<twohundredandnumber;
	cout<<endl;
	int twohundredandonenumber;
	twohundredandonenumber=201;
	cout<<twohundredandonenumber;
	cout<<endl;
	int twohundredandtwonumber;
	twohundredandtwonumber=202;
	cout<<twohundredandtwonumber;
	cout<<endl;
	int twohundredandtreenumber;
	twohundredandtreenumber=203;
	cout<<twohundredandtreenumber;
	cout<<endl;
	int twohundredandfournumber;
	twohundredandfournumber=204;
	cout<<twohundredandfournumber;
	cout<<endl;
	int twohundredandfivenumber;
	twohundredandfivenumber=205;
	cout<<twohundredandfivenumber;
	cout<<endl;
	int twohundredandsixnumber;
	twohundredandsixnumber=206;
	cout<<twohundredandsixnumber;
	cout<<endl;
	int twohundredandsevennumber;
	twohundredandsevennumber=207;
	cout<<twohundredandsevennumber;
	cout<<endl;
	int twohundredandeightnumber;
	twohundredandeightnumber=208;
	cout<<twohundredandeightnumber;
	cout<<endl;
	int twohundredandninenumber;
	twohundredandninenumber=209;
	cout<<twohundredandninenumber;
	cout<<endl;
	int twohundredandtennumber;
	twohundredandtennumber=210;
	cout<<twohundredandtennumber;
	cout<<endl;
	int twohundredandelevennumber;
	twohundredandelevennumber=211;
	cout<<twohundredandelevennumber;
	cout<<endl;
	int twohundredandtewelenumber;
	twohundredandtewelenumber=212;
	cout<<twohundredandtewelenumber;
	cout<<endl;
	int twohundredandthirteennumber;
	twohundredandthirteennumber=213;
	cout<<twohundredandthirteennumber;
	cout<<endl;
	int twohundredandfourteennumber;
	twohundredandfourteennumber=214;
	cout<<twohundredandfourteennumber;
	cout<<endl;
	int twohundredandfifteennumber;
	twohundredandfifteennumber=215;
	cout<<twohundredandfifteennumber;
	cout<<endl;
	int twohundredandsixteennumber;
	twohundredandsixteennumber=216;
	cout<<twohundredandsixteennumber;
	cout<<endl;
	int twohundredandseventeennumber;
	twohundredandseventeennumber=217;
	cout<<twohundredandseventeennumber;
	cout<<endl;
	int twohundredandeighteennumber;
	twohundredandeighteennumber=218;
	cout<<twohundredandeighteennumber;
	cout<<endl;
	int twohundredandninteennumber;
	twohundredandninteennumber=219;
	cout<<twohundredandninteennumber;
	cout<<endl;
	int twohundredandtewentynumber;
	twohundredandtewentynumber=220;
	cout<<twohundredandtewentynumber;
	cout<<endl;
	int twohundredandtewentyonenumber;
	twohundredandtewentyonenumber=221;
	cout<<twohundredandtewentyonenumber;
	cout<<endl;
	int twohundredandtewentytwonumber;
	twohundredandtewentytwonumber=222;
	cout<<twohundredandtewentytwonumber;
	cout<<endl;
	int twohundredandtewentytreenumber;
	twohundredandtewentytreenumber=223;
	cout<<twohundredandtewentytreenumber;
	cout<<endl;
	int twohundredandtewentyfournumber;
	twohundredandtewentyfournumber=224;
	cout<<twohundredandtewentyfournumber;
	cout<<endl;
	int twohundredandtewentyfivenumber;
	twohundredandtewentyfivenumber=225;
	cout<<twohundredandtewentyfivenumber;
	cout<<endl;
	int twohundredandtewentysixnumber;
	twohundredandtewentysixnumber=226;
	cout<<twohundredandtewentysixnumber;
	cout<<endl;
	int twohundredandtewentysevennumber;
	twohundredandtewentysevennumber=227;
	cout<<twohundredandtewentysevennumber;
	cout<<endl;
	int twohundredandtewentyeightnumber;
	twohundredandtewentyeightnumber=228;
	cout<<twohundredandtewentyeightnumber;
	cout<<endl;
	int twohundredandtewentyninenumber;
	twohundredandtewentyninenumber=229;
	cout<<twohundredandtewentyninenumber;
	cout<<endl;
	int twohundredandthirtynumber;
	twohundredandthirtynumber=230;
	cout<<twohundredandthirtynumber;
	cout<<endl;
	int twohundredandthirtyonenumber;
	twohundredandthirtyonenumber=231;
	cout<<twohundredandthirtyonenumber;
	cout<<endl;
	int twohundredandthirtytwonumber;
	twohundredandthirtytwonumber=232;
	cout<<twohundredandthirtytwonumber;
	cout<<endl;\
	int twohundredandthirtytreenumber;
	twohundredandthirtytreenumber=233;
	cout<<twohundredandthirtytreenumber;
	cout<<endl;
	int twohundredandthirtyfournumber;
	twohundredandthirtyfournumber=234;
	cout<<twohundredandthirtyfournumber;
	cout<<endl;
	int twohundredandthirtyfivenumber;
	twohundredandthirtyfivenumber=235;
	cout<<twohundredandthirtyfivenumber;
	cout<<endl;
	int twohundredandthirtysixnumber;
	twohundredandthirtysixnumber=236;
	cout<<twohundredandthirtysixnumber;
	cout<<endl;
	int twohundredandthirtysevennumber;
	twohundredandthirtysevennumber=237;
	cout<<twohundredandthirtysevennumber;
	cout<<endl;
	int twohundredandthirtyeightnumber;
	twohundredandthirtyeightnumber=238;
	cout<<twohundredandthirtyeightnumber;
	cout<<endl;
	int twohundredandthirtyninenumber;
	twohundredandthirtyninenumber=239;
	cout<<twohundredandthirtyninenumber;
	cout<<endl;
	int twohundredandfourtynumber;
	twohundredandfourtynumber=240;
	cout<<twohundredandfourtynumber;
	cout<<endl;
	int twohundredandfourtyonenumber;
	twohundredandfourtyonenumber=241;
	cout<<twohundredandfourtyonenumber;
	cout<<endl;
	int twohundredandfourtytwonumber;
	twohundredandfourtytwonumber=242;
	cout<<twohundredandfourtytwonumber;
	cout<<endl;
	int twohundredandfourtytreenumber;
	twohundredandfourtytreenumber=243;
	cout<<twohundredandfourtytreenumber;
	cout<<endl;
	int twohundredandfourtyfournumber;
	twohundredandfourtyfournumber=244;
	cout<<twohundredandfourtyfournumber;
	cout<<endl;
	int twohundredandfourtyfivenumber;
	twohundredandfourtyfivenumber=245;
	cout<<twohundredandfourtyfivenumber;
	cout<<endl;
	int twohundredandfourtysixnumber;
	twohundredandfourtysixnumber=246;
	cout<<twohundredandfourtysixnumber;
	cout<<endl;
	int twohundredandfourtysevennumber;
	twohundredandfourtysevennumber=247;
	cout<<twohundredandfourtysevennumber;
	cout<<endl;
	int twohundredandfourtyeightnumber;
	twohundredandfourtyeightnumber=248;
	cout<<twohundredandfourtyeightnumber;
	cout<<endl;
	int twohundredandfourtyninenumber;
	twohundredandfourtyninenumber=249;
	cout<<twohundredandfourtyninenumber;
	cout<<endl;
	int twohundredandfiftynumber;
	twohundredandfiftynumber=250;
	cout<<twohundredandfiftynumber;
	cout<<endl;
	int twohundredandfiftyonenumber;
	twohundredandfiftyonenumber=251;
	cout<<twohundredandfiftyonenumber;
	cout<<endl;
	int twohundredandfiftytwonumber;
	twohundredandfiftytwonumber=252;
	cout<<twohundredandfiftytwonumber;
	cout<<endl;
	int twohundredandfiftytreenumber;
	twohundredandfiftytreenumber=253;
	cout<<twohundredandfiftytreenumber;
	cout<<endl;
	int twohundredandfiftyfournumber;
	twohundredandfiftyfournumber=254;
	cout<<twohundredandfiftyfournumber;
	cout<<endl;
	int twohundredandfiftyfivenumber;
	twohundredandfiftyfivenumber=255;
	cout<<twohundredandfiftyfivenumber;
	cout<<endl;
	int twohundredandfiftysixnumber;
	twohundredandfiftysixnumber=256;
	cout<<twohundredandfiftysixnumber;
	cout<<endl;
	int twohundredandfiftysevennumber;
	twohundredandfiftysevennumber=257;
	cout<<twohundredandfiftysevennumber;
	cout<<endl;
	int twohundredandfiftyeightnumber;
	twohundredandfiftyeightnumber=258;
	cout<<twohundredandfiftyeightnumber;
	cout<<endl;
	int twohundredandfiftyninenumber;
	twohundredandfiftyninenumber=259;
	cout<<twohundredandfiftyninenumber;
	cout<<endl;
	int twohundredandsixtynumber;
	twohundredandsixtynumber=260;
	cout<<twohundredandsixtynumber;
	cout<<endl;
	int twohundredandsixtyonenumber;
	twohundredandsixtyonenumber=261;
	cout<<twohundredandsixtyonenumber;
	cout<<endl;
	int twohundredandsixtytwonumber;
	twohundredandsixtytwonumber=262;
	cout<<twohundredandsixtytwonumber;
	cout<<endl;
	int twohundredandsixtytreenumber;
	twohundredandsixtytreenumber=263;
	cout<<twohundredandsixtytreenumber;
	cout<<endl;
	int twohundredandsixtyfournumber;
	twohundredandsixtyfournumber=264;
	cout<<twohundredandsixtyfournumber;
	cout<<endl;
	int twohundredandsixtyfivenumber;
	twohundredandsixtyfivenumber=265;
	cout<<twohundredandsixtyfivenumber;
	cout<<endl;
	int twohundredandsixtysixnumber;
	twohundredandsixtysixnumber=266;
	cout<<twohundredandsixtysixnumber;
	cout<<endl;
	int twohundredandsixtysevennumber;
	twohundredandsixtysevennumber=267;
	cout<<twohundredandsixtysevennumber;
	cout<<endl;
	int twohundredandsixtyeightnumber;
	twohundredandsixtyeightnumber=268;
	cout<<twohundredandsixtyeightnumber;
	cout<<endl;
	int twohundredandsixtyninenumber;
	twohundredandsixtyninenumber=269;
	cout<<twohundredandsixtyninenumber;
	cout<<endl;
	int twohundredandseventynumber;
	twohundredandseventynumber=270;
	cout<<twohundredandseventynumber;
	cout<<endl;
	int twohundredandseventyonenumber;
	twohundredandseventyonenumber=271;
	cout<<twohundredandseventyonenumber;
	cout<<endl;
	int twohundredandseventytwonumber;
	twohundredandseventytwonumber=272;
	cout<<twohundredandseventytwonumber;
	cout<<endl;
	int twohundredandseventytreenumber;
	twohundredandseventytreenumber=273;
	cout<<twohundredandseventytreenumber;
	cout<<endl;
	int twohundredandseventyfournumber;
	twohundredandseventyfournumber=274;
	cout<<twohundredandseventyfournumber;
	cout<<endl;
	int twohundredandseventyfivenumber;
	twohundredandseventyfivenumber=275;
	cout<<twohundredandseventyfivenumber;
	cout<<endl;
	int twohundredandseventysixnumber;
	twohundredandseventysixnumber=276;
	cout<<twohundredandseventysixnumber;
	cout<<endl;
	int twohundredandseventysevennumber;
	twohundredandseventysevennumber=277;
	cout<<twohundredandseventysevennumber;
	cout<<endl;
	int twohundredandseventyeightnumber;
	twohundredandseventyeightnumber=278;
	cout<<twohundredandseventyeightnumber;
	cout<<endl;
	int twohundredandseventyninenumber;
	twohundredandseventyninenumber=279;
	cout<<twohundredandseventyninenumber;
	cout<<endl;
	int twohundredandeightynumber;
	twohundredandeightynumber=280;
	cout<<twohundredandeightynumber;
	cout<<endl;
	int twohundredandeightyonenumber;
	twohundredandeightyonenumber=281;
	cout<<twohundredandeightyonenumber;
	cout<<endl;
	int twohundredandeightytwonumber;
	twohundredandeightytwonumber=282;
	cout<<twohundredandeightytwonumber;
	cout<<endl;
	int twohundredandeightytreenumber;
	twohundredandeightytreenumber=283;
	cout<<twohundredandeightytreenumber;
	cout<<endl;
	int twohundredandeightyfournumber;
	twohundredandeightyfournumber=284;
	cout<<twohundredandeightyfournumber;
	cout<<endl;
	int twohundredandeightyfivenumber;
	twohundredandeightyfivenumber=285;
	cout<<twohundredandeightyfivenumber;
	cout<<endl;
	int twohundredandeightysixnumber;
	twohundredandeightysixnumber=286;
	cout<<twohundredandeightysixnumber;
	cout<<endl;
	int twohundredandeightysevennumber;
	twohundredandeightysevennumber=287;
	cout<<twohundredandeightysevennumber;
	cout<<endl;
	int twohundredandeightyeightnumber;
	twohundredandeightyeightnumber=288;
	cout<<twohundredandeightyeightnumber;
	cout<<endl;
	int twohundredandeightyninenumber;
	twohundredandeightyninenumber=289;
	cout<<twohundredandeightyninenumber;
	cout<<endl;
	int twohundredandnintynumber;
	twohundredandnintynumber=290;
	cout<<twohundredandnintynumber;
	cout<<endl;
	int twohundredandnintyonenumber;
	twohundredandnintyonenumber=291;
	cout<<twohundredandnintyonenumber;
	cout<<endl;
	int twohundredandnintytwonumber;
	twohundredandnintytwonumber=292;
	cout<<twohundredandnintytwonumber;
	cout<<endl;
	int twohundredandnintytreenumber;
	twohundredandnintytreenumber=293;
	cout<<twohundredandnintytreenumber;
	cout<<endl;
	int twohundredandnintyfournumber;
	twohundredandnintyfournumber=294;
	cout<<twohundredandnintyfournumber;
	cout<<endl;
	int twohundredandnintyfivenumber;
	twohundredandnintyfivenumber=295;
	cout<<twohundredandnintyfivenumber;
	cout<<endl;
    int twohundredandnintysixnumber;
	twohundredandnintysixnumber=296;
	cout<<twohundredandnintysixnumber;
	cout<<endl;
	int twohundredandnintysevennumber;
	twohundredandnintysevennumber=297;
	cout<<twohundredandnintysevennumber;
	cout<<endl;
	int twohundredandnintyeightnumber;
	twohundredandnintyeightnumber=298;
	cout<<twohundredandnintyeightnumber;
	cout<<endl;
	int twohundredandnintyninenumber;
	twohundredandnintyninenumber=299;
	cout<<twohundredandnintyninenumber;
	cout<<endl;
	int treehundrednumber;
	treehundrednumber=300;
	cout<<treehundrednumber;
	cout<<endl;
	int treehundredandonenumber;
	treehundredandonenumber=301;
	cout<<treehundredandonenumber;
	cout<<endl;
	int treehundredandtwonumber;
	treehundredandtwonumber=302;
	cout<<treehundredandtwonumber;
	cout<<endl;
	int treehundredandtreenumber;
	treehundredandtreenumber=303;
	cout<<treehundredandtreenumber;
	cout<<endl;
	int treehundredandfournumber;
	treehundredandfournumber=304;
	cout<<treehundredandfournumber;
	cout<<endl;
	int treehundredandfivenumber;
	treehundredandfivenumber=305;
	cout<<treehundredandfivenumber;
	cout<<endl;
	int treehundredandsixnumber;
	treehundredandsixnumber=306;
	cout<<treehundredandsixnumber;
	cout<<endl;
	int treehundredandsevennumber;
	treehundredandsevennumber=307;
	cout<<treehundredandsevennumber;
	cout<<endl;
	int treehundredandeightnumber;
	treehundredandeightnumber=308;
	cout<<treehundredandeightnumber;
	cout<<endl;
	int treehundredandninenumber;
	treehundredandninenumber=309;
	cout<<treehundredandninenumber;
	cout<<endl;
	int treehundredandtennumber;
	treehundredandtennumber=310;
	cout<<treehundredandtennumber;
	cout<<endl;
	int treehundredandelevennumber;
	treehundredandelevennumber=311;
	cout<<treehundredandelevennumber;
	cout<<endl;
	int treehundredandtewelenumber;
	treehundredandtewelenumber=312;
	cout<<treehundredandtewelenumber;
	cout<<endl;
	int treehundredandthirteennumber;
	treehundredandthirteennumber=313;
	cout<<treehundredandthirteennumber;
	cout<<endl;
	int treehundredandfourteennumber;
	treehundredandfourteennumber=314;
	cout<<treehundredandfourteennumber;
	cout<<endl;
	int treehundredandfifteennumber;
	treehundredandfifteennumber=315;
	cout<<treehundredandfifteennumber;
	cout<<endl;
	int treehundredandsixteennumber;
	treehundredandsixteennumber=316;
	cout<<treehundredandsixteennumber;
	cout<<endl;
	int treehundredandseventeennumber;
	treehundredandseventeennumber=317;
	cout<<treehundredandseventeennumber;
	cout<<endl;
	int treehundredandeighteennumber;
	treehundredandeighteennumber=318;
	cout<<treehundredandeighteennumber;
	cout<<endl;
	int treehundredandninteennumber;
	treehundredandninteennumber=319;
	cout<<treehundredandninteennumber;
	cout<<endl;
	int treehundredandtewentynumber;
	treehundredandtewentynumber=320;
	cout<<treehundredandtewentynumber;
	cout<<endl;
	int treehundredandtewentyonenumber;
	treehundredandtewentyonenumber=321;
	cout<<treehundredandtewentyonenumber;
	cout<<endl;
	int treehundredandtewentytwonumber;
	treehundredandtewentytwonumber=322;
	cout<<treehundredandtewentytwonumber;
	cout<<endl;
	int treehundredandtewentytreenumber;
	treehundredandtewentytreenumber=323;
	cout<<treehundredandtewentytreenumber;
	cout<<endl;
	int treehundredandtewentyfournumber;
	treehundredandtewentyfournumber=324;
	cout<<treehundredandtewentyfournumber;
	cout<<endl;
	int treehundredandtewentyfivenumber;
	treehundredandtewentyfivenumber=325;
	cout<<treehundredandtewentyfivenumber;
	cout<<endl;
	int treehundredandtewentysixnumber;
	treehundredandtewentysixnumber=326;
	cout<<treehundredandtewentysixnumber;
	cout<<endl;
	int treehundredandtewentysevennumber;
	treehundredandtewentysevennumber=327;
	cout<<treehundredandtewentysevennumber;
	cout<<endl;
	int treehundredandtewentyeightnumber;
	treehundredandtewentyeightnumber=328;
	cout<<treehundredandtewentyeightnumber;
	cout<<endl;
	int treehundredandtewentyninenumber;
	treehundredandtewentyninenumber=329;
	cout<<treehundredandtewentyninenumber;
	cout<<endl;
	int treehundredandthirtynumber;
	treehundredandthirtynumber=330;
	cout<<treehundredandthirtynumber;
	cout<<endl;
	int treehundredandthirtyonenumber;
	treehundredandthirtyonenumber=331;
	cout<<treehundredandthirtyonenumber;
	cout<<endl;
	int treehundredandthirtytwonumber;
	treehundredandthirtytwonumber=332;
	cout<<treehundredandthirtytwonumber;
	cout<<endl;\
	int treehundredandthirtytreenumber;
	treehundredandthirtytreenumber=333;
	cout<<treehundredandthirtytreenumber;
	cout<<endl;
	int treehundredandthirtyfournumber;
	treehundredandthirtyfournumber=334;
	cout<<treehundredandthirtyfournumber;
	cout<<endl;
	int treehundredandthirtyfivenumber;
	treehundredandthirtyfivenumber=335;
	cout<<treehundredandthirtyfivenumber;
	cout<<endl;
	int treehundredandthirtysixnumber;
	treehundredandthirtysixnumber=336;
	cout<<treehundredandthirtysixnumber;
	cout<<endl;
	int treehundredandthirtysevennumber;
	treehundredandthirtysevennumber=337;
	cout<<treehundredandthirtysevennumber;
	cout<<endl;
	int treehundredandthirtyeightnumber;
	treehundredandthirtyeightnumber=338;
	cout<<treehundredandthirtyeightnumber;
	cout<<endl;
	int treehundredandthirtyninenumber;
	treehundredandthirtyninenumber=339;
	cout<<treehundredandthirtyninenumber;
	cout<<endl;
	int treehundredandfourtynumber;
	treehundredandfourtynumber=340;
	cout<<treehundredandfourtynumber;
	cout<<endl;
	int treehundredandfourtyonenumber;
	treehundredandfourtyonenumber=341;
	cout<<treehundredandfourtyonenumber;
	cout<<endl;
	int treehundredandfourtytwonumber;
	treehundredandfourtytwonumber=342;
	cout<<treehundredandfourtytwonumber;
	cout<<endl;
	int treehundredandfourtytreenumber;
	treehundredandfourtytreenumber=343;
	cout<<treehundredandfourtytreenumber;
	cout<<endl;
	int treehundredandfourtyfournumber;
	treehundredandfourtyfournumber=344;
	cout<<treehundredandfourtyfournumber;
	cout<<endl;
	int treehundredandfourtyfivenumber;
	treehundredandfourtyfivenumber=345;
	cout<<treehundredandfourtyfivenumber;
	cout<<endl;
	int treehundredandfourtysixnumber;
	treehundredandfourtysixnumber=346;
	cout<<treehundredandfourtysixnumber;
	cout<<endl;
	int treehundredandfourtysevennumber;
	treehundredandfourtysevennumber=347;
	cout<<treehundredandfourtysevennumber;
	cout<<endl;
	int treehundredandfourtyeightnumber;
	treehundredandfourtyeightnumber=348;
	cout<<treehundredandfourtyeightnumber;
	cout<<endl;
	int treehundredandfourtyninenumber;
	treehundredandfourtyninenumber=349;
	cout<<treehundredandfourtyninenumber;
	cout<<endl;
	int treehundredandfiftynumber;
	treehundredandfiftynumber=350;
	cout<<treehundredandfiftynumber;
	cout<<endl;
	int treehundredandfiftyonenumber;
	treehundredandfiftyonenumber=351;
	cout<<treehundredandfiftyonenumber;
	cout<<endl;
	int treehundredandfiftytwonumber;
	treehundredandfiftytwonumber=352;
	cout<<treehundredandfiftytwonumber;
	cout<<endl;
	int treehundredandfiftytreenumber;
	treehundredandfiftytreenumber=353;
	cout<<treehundredandfiftytreenumber;
	cout<<endl;
	int treehundredandfiftyfournumber;
	treehundredandfiftyfournumber=354;
	cout<<treehundredandfiftyfournumber;
	cout<<endl;
	int treehundredandfiftyfivenumber;
	treehundredandfiftyfivenumber=355;
	cout<<treehundredandfiftyfivenumber;
	cout<<endl;
	int treehundredandfiftysixnumber;
	treehundredandfiftysixnumber=356;
	cout<<treehundredandfiftysixnumber;
	cout<<endl;
	int treehundredandfiftysevennumber;
	treehundredandfiftysevennumber=357;
	cout<<treehundredandfiftysevennumber;
	cout<<endl;
	int treehundredandfiftyeightnumber;
	treehundredandfiftyeightnumber=358;
	cout<<treehundredandfiftyeightnumber;
	cout<<endl;
	int treehundredandfiftyninenumber;
	treehundredandfiftyninenumber=359;
	cout<<treehundredandfiftyninenumber;
	cout<<endl;
	int treehundredandsixtynumber;
	treehundredandsixtynumber=360;
	cout<<treehundredandsixtynumber;
	cout<<endl;
	int treehundredandsixtyonenumber;
	treehundredandsixtyonenumber=361;
	cout<<treehundredandsixtyonenumber;
	cout<<endl;
	int treehundredandsixtytwonumber;
	treehundredandsixtytwonumber=362;
	cout<<treehundredandsixtytwonumber;
	cout<<endl;
	int treehundredandsixtytreenumber;
	treehundredandsixtytreenumber=363;
	cout<<treehundredandsixtytreenumber;
	cout<<endl;
	int treehundredandsixtyfournumber;
	treehundredandsixtyfournumber=364;
	cout<<treehundredandsixtyfournumber;
	cout<<endl;
	int treehundredandsixtyfivenumber;
	treehundredandsixtyfivenumber=365;
	cout<<treehundredandsixtyfivenumber;
	cout<<endl;
	int treehundredandsixtysixnumber;
	treehundredandsixtysixnumber=366;
	cout<<treehundredandsixtysixnumber;
	cout<<endl;
	int treehundredandsixtysevennumber;
	treehundredandsixtysevennumber=367;
	cout<<treehundredandsixtysevennumber;
	cout<<endl;
	int treehundredandsixtyeightnumber;
	treehundredandsixtyeightnumber=368;
	cout<<treehundredandsixtyeightnumber;
	cout<<endl;
	int treehundredandsixtyninenumber;
	treehundredandsixtyninenumber=369;
	cout<<treehundredandsixtyninenumber;
	cout<<endl;
	int treehundredandseventynumber;
	treehundredandseventynumber=370;
	cout<<treehundredandseventynumber;
	cout<<endl;
	int treehundredandseventyonenumber;
	treehundredandseventyonenumber=371;
	cout<<treehundredandseventyonenumber;
	cout<<endl;
	int treehundredandseventytwonumber;
	treehundredandseventytwonumber=372;
	cout<<treehundredandseventytwonumber;
	cout<<endl;
	int treehundredandseventytreenumber;
	treehundredandseventytreenumber=373;
	cout<<treehundredandseventytreenumber;
	cout<<endl;
	int treehundredandseventyfournumber;
    treehundredandseventyfournumber=374;
	cout<<treehundredandseventyfournumber;
	cout<<endl;
	int treehundredandseventyfivenumber;
	treehundredandseventyfivenumber=375;
	cout<<treehundredandseventyfivenumber;
	cout<<endl;
	int treehundredandseventysixnumber;
	treehundredandseventysixnumber=376;
	cout<<treehundredandseventysixnumber;
	cout<<endl;
	int treehundredandseventysevennumber;
	treehundredandseventysevennumber=377;
	cout<<treehundredandseventysevennumber;
	cout<<endl;
	int treehundredandseventyeightnumber;
	treehundredandseventyeightnumber=378;
	cout<<treehundredandseventyeightnumber;
	cout<<endl;
	int treehundredandseventyninenumber;
	treehundredandseventyninenumber=379;
	cout<<treehundredandseventyninenumber;
	cout<<endl;
	int treehundredandeightynumber;
	treehundredandeightynumber=380;
	cout<<treehundredandeightynumber;
	cout<<endl;
	int treehundredandeightyonenumber;
	treehundredandeightyonenumber=381;
	cout<<treehundredandeightyonenumber;
	cout<<endl;
	int treehundredandeightytwonumber;
	treehundredandeightytwonumber=382;
	cout<<treehundredandeightytwonumber;
	cout<<endl;
	int treehundredandeightytreenumber;
	treehundredandeightytreenumber=383;
	cout<<treehundredandeightytreenumber;
	cout<<endl;
	int treehundredandeightyfournumber;
	treehundredandeightyfournumber=384;
	cout<<treehundredandeightyfournumber;
	cout<<endl;
	int treehundredandeightyfivenumber;
	treehundredandeightyfivenumber=385;
	cout<<treehundredandeightyfivenumber;
	cout<<endl;
	int treehundredandeightysixnumber;
	treehundredandeightysixnumber=386;
	cout<<treehundredandeightysixnumber;
	cout<<endl;
	int treehundredandeightysevennumber;
	treehundredandeightysevennumber=387;
	cout<<treehundredandeightysevennumber;
	cout<<endl;
	int treehundredandeightyeightnumber;
	treehundredandeightyeightnumber=388;
	cout<<treehundredandeightyeightnumber;
	cout<<endl;
	int treehundredandeightyninenumber;
	treehundredandeightyninenumber=389;
	cout<<treehundredandeightyninenumber;
	cout<<endl;
	int treehundredandnintynumber;
	treehundredandnintynumber=390;
	cout<<treehundredandnintynumber;
	cout<<endl;
	int treehundredandnintyonenumber;
	treehundredandnintyonenumber=391;
	cout<<treehundredandnintyonenumber;
	cout<<endl;
	int treehundredandnintytwonumber;
	treehundredandnintytwonumber=392;
	cout<<treehundredandnintytwonumber;
	cout<<endl;
	int treehundredandnintytreenumber;
	treehundredandnintytreenumber=393;
	cout<<treehundredandnintytreenumber;
	cout<<endl;
	int treehundredandnintyfournumber;
	treehundredandnintyfournumber=394;
	cout<<treehundredandnintyfournumber;
	cout<<endl;
	int treehundredandnintyfivenumber;
	treehundredandnintyfivenumber=395;
	cout<<treehundredandnintyfivenumber;
	cout<<endl;
    int treehundredandnintysixnumber;
	treehundredandnintysixnumber=396;
	cout<<treehundredandnintysixnumber;
	cout<<endl;
	int treehundredandnintysevennumber;
	treehundredandnintysevennumber=397;
	cout<<treehundredandnintysevennumber;
	cout<<endl;
	int treehundredandnintyeightnumber;
	treehundredandnintyeightnumber=398;
	cout<<treehundredandnintyeightnumber;
	cout<<endl;
	int treehundredandnintyninenumber;
	treehundredandnintyninenumber=399;
	cout<<treehundredandnintyninenumber;
	cout<<endl;
	int fourhundred;
    fourhundred=400;
	cout<<fourhundred;
}
