#include<iostream>
using namespace std;
int
main()
{
	char a[1],b[1],c[1],d[1],e[1],f[1],g[1],h[1],i[1],j[1],k[1],l[1],m[1],n[1],o[1],p[1],q[1],r[1],s[1],t[1],u[1],v[1],w[1],x[1],y[1],z[1];
	cout<<"\t\t\t \f|={talking with friend}=|\f\n\n\n";
	cout<<" salam\n\n";
	cin>>a;
	cout<<endl;
	cout<<"kesy ho\n\n";
	cin>>b;
	cout<<endl;
	cin>>c;
	cout<<endl;
	cout<<"me bee teek hoo\n\n";
	cout<<"kya kar rahe hoo app\n\n";
	cout<<endl;
	cin>>d;
	cout<<endl;
	cout<<"ghar wale kese he\n\n";
	cin>>e;
	cout<<endl;
	cin>>f;
	cout<<"me call of duty world war 2 game kheel raha ho\n\n";
	cin>>g;
	cout<<endl;
	cout<<"kya ap ne kabi kheela he\n\n";
	cin>>h;
	cout<<endl;
	cout<<"oh bohat zabardust game he\n\n";
	cin>>i;
	cout<<endl;
	cout<<"me ap keleye bakupe le aoo game ka\n\n";
	cin>>j;
	cout<<endl;
	cout<<"acha apke pass usb to he\n\n";
	cin>>k;
	cout<<endl;
	cout<<"ketny gb usb he\n\n";
	cin>>l;
	cout<<endl;
	cout<<"acha me kahi se usb ka intezam karta ho\n\n";
	cin>>m;
	cout<<endl;
	cout<<"per ap ke pass system konsa he\n\n";
	cin>>n;
	cout<<endl;
	cout<<"core i 3\n\n";
	cin>>o;
	cout<<endl;
	cout<<"os me vedio card he mean 3d card\n\n";
	cin>>p;
	cout<<endl;
	cout<<"konsa card he\n\n";
	cin>>q;
	cout<<endl;
	cout<<"2 gb he ke 1 gb\n\n";
	cin>>r;
	cout<<endl;
	cout<<"128 bit he\n\n";
	cin>>s;
	cout<<endl;
	cout<<"me kal le ga hard disk me\n\n";
	cin>>t;
	cout<<endl;
	cout<<"hard disk ka keet to hee na\n\n";
	cin>>u;
	cout<<endl;
	cout<<"me kal ketne bage aoo\n\n";
	cin>>v;
	cout<<endl;
	cout<<"acha me ab jaa raha ho\n\n";
	cin>>w;
	cout<<endl;
	cout<<"acha kal college aoo ge\n\n";
	cin>>x;
	cout<<endl;
	cout<<"me bee kal aoo gaa\n\n";
	cin>>y;
	cout<<endl;
	cout<<"acha mery taraf apne ghar walo ko salam karna ok good by\n\n";
	cin>>z;
}
